pp User.create(name: 'admin', email: 'admin@admin.com', password: '123456')
pp user = User.create(name: 'user', email: 'user@user.com', password: '123456')
pp other_user = User.create(name: 'other_user', email: 'other_user@user.com', password: '123456')

pp publisher = Publisher.create!(name: 'publisher')
pp other_publisher = Publisher.create!(name: 'other_publisher')

pp book1 = Book.create!(title: 'book1', publisher: publisher)
pp book2 = Book.create!(title: 'book2', publisher: publisher)
pp book3 = Book.create!(title: 'book3', publisher: other_publisher)
pp book4 = Book.create!(title: 'book4', publisher: other_publisher)

pp shop1 = Shop.create!(name: 'shop1')
pp shop2 = Shop.create!(name: 'shop2')

pp shop1.add_book(book1)
pp shop1.add_book(book2)
pp shop1.add_book(book2)
pp shop1.add_book(book3)
pp shop1.add_book(book3)
pp shop1.add_book(book3)
pp shop1.add_book(book4)
pp shop1.add_book(book4)
pp shop1.add_book(book4)
pp shop1.add_book(book4)
pp shop2.add_book(book1)
pp shop2.add_book(book1)
pp shop2.add_book(book1)
pp shop2.add_book(book1)
pp shop2.add_book(book2)
pp shop2.add_book(book2)
pp shop2.add_book(book2)
pp shop2.add_book(book3)
pp shop2.add_book(book3)
pp shop2.add_book(book4)
